[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions"

[redirects]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200